<?php
/**
 * @file
 * Contains administration functions for the Configuration Builder module.
 */

/**
 * Include additional files.
 */
foreach (module_list() as $module) {
  if (file_exists($file = dirname(__FILE__) . "/includes/{$module}.inc")) {
    require_once $file;
  }
}

/**
 * Implements hook_permission().
 */
function config_builder_ui_permission() {
  return array(
    'administer config builder' => array(
      'title' => t('Administer Configuration builder'),
    ),
  );
}

/**
 * Implements hook_flush_caches().
 */
function config_builder_flush_caches() {
//  db_delete('form_builder_cache')
//    ->condition('type', 'config_builder')
//    ->execute();
  form_builder_crud_index_save();
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function config_builder_ui_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/{$plugin}";
  }
}
